/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package point.io.securevault.service.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-02-10")
public class TProvider implements org.apache.thrift.TBase<TProvider, TProvider._Fields>, java.io.Serializable, Cloneable, Comparable<TProvider> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TProvider");

  private static final org.apache.thrift.protocol.TField TASKNAME_FIELD_DESC = new org.apache.thrift.protocol.TField("taskname", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField TASKKEY_FIELD_DESC = new org.apache.thrift.protocol.TField("taskkey", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField PROVIDERID_FIELD_DESC = new org.apache.thrift.protocol.TField("providerid", org.apache.thrift.protocol.TType.STRING, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TProviderStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TProviderTupleSchemeFactory());
  }

  public String taskname; // optional
  public String taskkey; // optional
  public String providerid; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TASKNAME((short)1, "taskname"),
    TASKKEY((short)2, "taskkey"),
    PROVIDERID((short)3, "providerid");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TASKNAME
          return TASKNAME;
        case 2: // TASKKEY
          return TASKKEY;
        case 3: // PROVIDERID
          return PROVIDERID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields optionals[] = {_Fields.TASKNAME,_Fields.TASKKEY,_Fields.PROVIDERID};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TASKNAME, new org.apache.thrift.meta_data.FieldMetaData("taskname", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , "Text")));
    tmpMap.put(_Fields.TASKKEY, new org.apache.thrift.meta_data.FieldMetaData("taskkey", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , "Text")));
    tmpMap.put(_Fields.PROVIDERID, new org.apache.thrift.meta_data.FieldMetaData("providerid", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , "Text")));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TProvider.class, metaDataMap);
  }

  public TProvider() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TProvider(TProvider other) {
    if (other.isSetTaskname()) {
      this.taskname = other.taskname;
    }
    if (other.isSetTaskkey()) {
      this.taskkey = other.taskkey;
    }
    if (other.isSetProviderid()) {
      this.providerid = other.providerid;
    }
  }

  public TProvider deepCopy() {
    return new TProvider(this);
  }

  @Override
  public void clear() {
    this.taskname = null;
    this.taskkey = null;
    this.providerid = null;
  }

  public String getTaskname() {
    return this.taskname;
  }

  public TProvider setTaskname(String taskname) {
    this.taskname = taskname;
    return this;
  }

  public void unsetTaskname() {
    this.taskname = null;
  }

  /** Returns true if field taskname is set (has been assigned a value) and false otherwise */
  public boolean isSetTaskname() {
    return this.taskname != null;
  }

  public void setTasknameIsSet(boolean value) {
    if (!value) {
      this.taskname = null;
    }
  }

  public String getTaskkey() {
    return this.taskkey;
  }

  public TProvider setTaskkey(String taskkey) {
    this.taskkey = taskkey;
    return this;
  }

  public void unsetTaskkey() {
    this.taskkey = null;
  }

  /** Returns true if field taskkey is set (has been assigned a value) and false otherwise */
  public boolean isSetTaskkey() {
    return this.taskkey != null;
  }

  public void setTaskkeyIsSet(boolean value) {
    if (!value) {
      this.taskkey = null;
    }
  }

  public String getProviderid() {
    return this.providerid;
  }

  public TProvider setProviderid(String providerid) {
    this.providerid = providerid;
    return this;
  }

  public void unsetProviderid() {
    this.providerid = null;
  }

  /** Returns true if field providerid is set (has been assigned a value) and false otherwise */
  public boolean isSetProviderid() {
    return this.providerid != null;
  }

  public void setProvideridIsSet(boolean value) {
    if (!value) {
      this.providerid = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case TASKNAME:
      if (value == null) {
        unsetTaskname();
      } else {
        setTaskname((String)value);
      }
      break;

    case TASKKEY:
      if (value == null) {
        unsetTaskkey();
      } else {
        setTaskkey((String)value);
      }
      break;

    case PROVIDERID:
      if (value == null) {
        unsetProviderid();
      } else {
        setProviderid((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case TASKNAME:
      return getTaskname();

    case TASKKEY:
      return getTaskkey();

    case PROVIDERID:
      return getProviderid();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case TASKNAME:
      return isSetTaskname();
    case TASKKEY:
      return isSetTaskkey();
    case PROVIDERID:
      return isSetProviderid();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TProvider)
      return this.equals((TProvider)that);
    return false;
  }

  public boolean equals(TProvider that) {
    if (that == null)
      return false;

    boolean this_present_taskname = true && this.isSetTaskname();
    boolean that_present_taskname = true && that.isSetTaskname();
    if (this_present_taskname || that_present_taskname) {
      if (!(this_present_taskname && that_present_taskname))
        return false;
      if (!this.taskname.equals(that.taskname))
        return false;
    }

    boolean this_present_taskkey = true && this.isSetTaskkey();
    boolean that_present_taskkey = true && that.isSetTaskkey();
    if (this_present_taskkey || that_present_taskkey) {
      if (!(this_present_taskkey && that_present_taskkey))
        return false;
      if (!this.taskkey.equals(that.taskkey))
        return false;
    }

    boolean this_present_providerid = true && this.isSetProviderid();
    boolean that_present_providerid = true && that.isSetProviderid();
    if (this_present_providerid || that_present_providerid) {
      if (!(this_present_providerid && that_present_providerid))
        return false;
      if (!this.providerid.equals(that.providerid))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_taskname = true && (isSetTaskname());
    list.add(present_taskname);
    if (present_taskname)
      list.add(taskname);

    boolean present_taskkey = true && (isSetTaskkey());
    list.add(present_taskkey);
    if (present_taskkey)
      list.add(taskkey);

    boolean present_providerid = true && (isSetProviderid());
    list.add(present_providerid);
    if (present_providerid)
      list.add(providerid);

    return list.hashCode();
  }

  @Override
  public int compareTo(TProvider other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetTaskname()).compareTo(other.isSetTaskname());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTaskname()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.taskname, other.taskname);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTaskkey()).compareTo(other.isSetTaskkey());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTaskkey()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.taskkey, other.taskkey);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetProviderid()).compareTo(other.isSetProviderid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProviderid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.providerid, other.providerid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TProvider(");
    boolean first = true;

    if (isSetTaskname()) {
      sb.append("taskname:");
      if (this.taskname == null) {
        sb.append("null");
      } else {
        sb.append(this.taskname);
      }
      first = false;
    }
    if (isSetTaskkey()) {
      if (!first) sb.append(", ");
      sb.append("taskkey:");
      if (this.taskkey == null) {
        sb.append("null");
      } else {
        sb.append(this.taskkey);
      }
      first = false;
    }
    if (isSetProviderid()) {
      if (!first) sb.append(", ");
      sb.append("providerid:");
      if (this.providerid == null) {
        sb.append("null");
      } else {
        sb.append(this.providerid);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TProviderStandardSchemeFactory implements SchemeFactory {
    public TProviderStandardScheme getScheme() {
      return new TProviderStandardScheme();
    }
  }

  private static class TProviderStandardScheme extends StandardScheme<TProvider> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TProvider struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TASKNAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.taskname = iprot.readString();
              struct.setTasknameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // TASKKEY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.taskkey = iprot.readString();
              struct.setTaskkeyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // PROVIDERID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.providerid = iprot.readString();
              struct.setProvideridIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TProvider struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.taskname != null) {
        if (struct.isSetTaskname()) {
          oprot.writeFieldBegin(TASKNAME_FIELD_DESC);
          oprot.writeString(struct.taskname);
          oprot.writeFieldEnd();
        }
      }
      if (struct.taskkey != null) {
        if (struct.isSetTaskkey()) {
          oprot.writeFieldBegin(TASKKEY_FIELD_DESC);
          oprot.writeString(struct.taskkey);
          oprot.writeFieldEnd();
        }
      }
      if (struct.providerid != null) {
        if (struct.isSetProviderid()) {
          oprot.writeFieldBegin(PROVIDERID_FIELD_DESC);
          oprot.writeString(struct.providerid);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TProviderTupleSchemeFactory implements SchemeFactory {
    public TProviderTupleScheme getScheme() {
      return new TProviderTupleScheme();
    }
  }

  private static class TProviderTupleScheme extends TupleScheme<TProvider> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TProvider struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetTaskname()) {
        optionals.set(0);
      }
      if (struct.isSetTaskkey()) {
        optionals.set(1);
      }
      if (struct.isSetProviderid()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetTaskname()) {
        oprot.writeString(struct.taskname);
      }
      if (struct.isSetTaskkey()) {
        oprot.writeString(struct.taskkey);
      }
      if (struct.isSetProviderid()) {
        oprot.writeString(struct.providerid);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TProvider struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.taskname = iprot.readString();
        struct.setTasknameIsSet(true);
      }
      if (incoming.get(1)) {
        struct.taskkey = iprot.readString();
        struct.setTaskkeyIsSet(true);
      }
      if (incoming.get(2)) {
        struct.providerid = iprot.readString();
        struct.setProvideridIsSet(true);
      }
    }
  }

}

